### ISSUE TITLE
OWAS GA4 data modelling

### ISSUE THREAD

**Issue by charles-astrafy** [Velir/dbt-ga4#105]
Hello,

We are starting to use this package and were wondering the difference between the data modelling stated here:

https://support.owox.com/hc/en-us/articles/10477064761236-1-Sessions-stg-data-preparation-temp-sessions-

Are we right to assume that the facts and dims created in this dbt package sessionize through the following fact tables:
- fct_ga4__sessions
- fct_ga4__sessions_daily

Following tables are present in the website above and would be of interest to add in this package according to us:

- Events --> fact table
- Transactions --> fact table

Thank you for your feedback

**Comment by adamribaudo-velir** [comment]
Hi. There are lots of differences between this package and the script you linked to, but I think the intention is the same: to provide a high-level abstraction of GA4 data that is modeled and easy to use. 

You're correct that session-level data can be found in those 2 models, but don't forget this model as well: `dim_ga4__sessions`

One major difference is that our package supports incremental loading of facts, so that you avoid scanning the entire event table on every run. The script you linked makes very liberal use of window functions which means that every event will be scanned each time it runs. This can get expensive for large sites. 

Regarding events and transactions, you can find them here:
https://github.com/Velir/dbt-ga4/tree/main/models/staging/ga4/events
https://github.com/Velir/dbt-ga4/tree/main/models/staging/ga4/recommended_events

**Comment by charles-astrafy** [comment]
HI @adamribaudo-velir ,

Thanks a lot for your detailed answer. We will definitely take your dbt-ga4 package as our starting point and I have seen a TODO.md that we will certainly collaborate to.

We were also thinking about adding some generic dbt metrics via the new dbt semantic layer.
