### ISSUE TITLE
Multi-site: user_pseudo_id fails unique check

### ISSUE THREAD

**Issue by dgitis** [Velir/dbt-ga4#163]
The user_pseudo_id fails the unique check when used in multi-site.

The user_pseudo_id needs to be concatenated with the stream_id to pass this check.

**Comment by dgitis** [comment]
@adamribaudo  and @willbryant 

What do you two think about adding a `user_pseudo_key` to `stg_ga4__events` vs. simply replacing the `user_pseudo_id` with `to_base64(md5(concat(user_pseudo_id,stream_id)))`?

The first is consistent with what we have done in the past but also requires a bunch of changes to downstream models. The second is less destructive of reports built off of the package and easier to implement.

I could add an `original_user_pseudo_id` field for debug purposes if we go the second route.

**Comment by adamribaudo-velir** [comment]
I'm leaning towards the first suggestion (`user_psuedo_key`). I have a feeling that modifying the value of the `user_pseudo_id` column will cause a lot of confusion for package users who might be troubleshooting and would reasonably expect that value to be exactly what Google sets. 

This might be a good opportunity to create some more consistent naming and use the column name `device_key` so that the hierarchy of entities becomes:
- `user_id`
- - `device_key`
- - - `session_key`
- - - - `event_key`

Good catch.

**Comment by dgitis** [comment]
I'm assuming that `device_key` is what I was referring to as `user_pseudo_key`. I don't hate that name, but I immediately started thinking about device lookup tables and wondered why we would need those. 

How about `client_key`? It's send as the cid (for client ID) in the collection API, so there's some precedent. Client is also more accurate than device since you can have multiple clients on one device and the cid/user_pseudo_id corresponds to a client rather than a device.

**Comment by adamribaudo-velir** [comment]
I like it! Let's go with `client_key`

**Comment by willbryant** [comment]
Yep, sounds good. user_pseudo_key or client_key IMHO. Definitely agree not user_pseudo_id.
