### ISSUE TITLE
Database Error in model dim_ga4__sessions_daily

### ISSUE THREAD

**Issue by QingFyndiq** [Velir/dbt-ga4#229]
Hi,
I have updated the package to the latest one but meet a new database error duet to resources exceeded.

    03:32:07  Database Error in model dim_ga4__sessions_daily (models/marts/core/dim_ga4__sessions_daily.sql)
    03:32:07    Resources exceeded during query execution: The query could not be executed in the allotted memory. Peak usage: 123% of limit.
    03:32:07    Top memory consumer(s):
    03:32:07      sort operations used for analytic OVER() clauses: 100%
    03:32:07    
    03:32:07    compiled Code at target/run/ga4/models/marts/core/dim_ga4__sessions_daily.sql

 Is it possible to optimize the query instead of changing the database configuration?

**Comment by adamribaudo-velir** [comment]
Is this during the initial load or full refresh? Can you try to limit the `start_date` variable and see if it runs? If so, you may need to find a way to batch load all your data by day first and then use incremental runs moving forward. 

Otherwise, you're welcome to take a look at the SQL and optimize further.
