### ISSUE TITLE
Configurable session-scope click ID fields from referring site

### ISSUE THREAD

**Issue by dgitis** [Velir/dbt-ga4#234]
See the first comment for the current approach.

It seems that Google has a `gclid` alternative parameter specifically for iOS devices ([this post mentions them](https://tanelytics.com/ga4-bigquery-session-traffic_source/)) called either 'gbraid' or 'wbraid'.

We may want to change from extracting just `gclid` to letting users configure which click IDs are extracted into a new pair of name-value fields for storing which type of click ID you extract and its value.

**Comment by dgitis** [comment]
I'm thinking we might want to switch this to creating two new columns for `xclid_name` and `xclid_value` and then create a configurable xclid list variable like `xclid = ['gclid','fbclid','gbraid',wbraid']` that searches for URL parameters matching the name and then populates the name, value pairs with the click ID.

One possible issue with this approach is handling multiple xclids in a single URL. I presume that these parameters are mutually exclusive, but don't know.

**Comment by willbryant** [comment]
Checked my data. I haven't seen any with gclid & gbraid on the same URL, but interestingly I have seen them together on URLs in the same session.

We could use a repeated nested name/value field?

It would be good if people could easily add their own third-party ID fields (eg. klaviyo, braze, onesignal, etc etc.).

**Comment by adamribaudo-velir** [comment]
I'm not clear on the goal of the issue:

1. We currently don't extract the `gclid` values, we simply detect if `gclid` exists in the URL and set the UTM source medium to google / cpc if so. So I'm not following the comment "We may want to change from extracting just gclid to letting users configure which click IDs are extracted". Is the point of extracting the IDs to help with downstream linking with ad click data? Just not clear to me why we'd extract them now but didn't previously. 

2. The linked article discusses how GA4 handles sessions with multiple sources and how last-non-direct will pull the latest source in the previous session. So there's some sophisticated code making sure that last-non-direct works as intended in GA4 that we could borrow from. The name of this issue is "Session-scope click ID fields" so is the intention to apply this last-non-direct logic? Good if so, it's just not clear. 

3. Regarding paid ad click IDs, the article's take-away is that GCLID, GBRAID, WBRAID traffic cannot be determined and that "perhaps the best fix to this problem is to start including utm tags with the auto-tagged Google Ads traffic as well." Right now we hard-code `gclid` to `google / cpc` which clearly won't always be correct but I like it better than 
doing nothing which would result in a lot more inaccurate "direct / none" or "google / organic". We could include `GBRAID` and `WBRAID` in this evaluation to catch those as well. That would be an easy fix. 

There are potentially some good ideas here, just not sure if the goal is 1, 2, or 3

**Comment by dgitis** [comment]
Thanks for asking for clarification.

1. You are correct. The point is to enable downstream linking with ad click data.

2. I was only planning on apply it to unadulterated sessions. Before adding it to last, non-direct, we should have a discussion on whether we want to enable an ads-preferred model like GA4 does. Ours would be better, imo, because we'd be treating all ad IDs equally while Google's ads-preferred only prefers Google Ads.

3. This is not going to affect the source / medium attribution that we do on `gclid` parameters. I'm not sure if the `GBRAID` and `WBRAID` parameters suffer from the same source / medium attribution issues. Perhaps @willbryant can chime in on that. I'm not planning on fixing any potential source / medium issues in this PR.

The answer is 1. It's to simplify downstream linking with ad click data.

**Comment by adamribaudo-velir** [comment]
Thanks for clarifying! If that's the case, I suggest we use the new `extract_query_parameter_value` macro you created to keep this generic to any query parameter. There's no need to treat click IDs different than any other query parameter. 

Also, I suggest we create new columns for these values. Storing the data as an array is useful when the shape of the data will change from event to event. But if the configuration occurs at the project level, then the shape is consistent for every event. Keeping the data "flat" is also helpful for those pushing this data into other storage formats. 

I can work on this now.

**Comment by adamribaudo-velir** [comment]
Draft PR is here. I'd like to add unit tests for the macro is all. Can work on that later:

https://github.com/Velir/dbt-ga4/pull/252
