### ISSUE TITLE
Multi-Property Support with streaming intraday tables

### ISSUE THREAD

**Issue by FlorianASchroeder** [Velir/dbt-ga4#254]
Due to a recent change in #250 it is not possible anymore to use multiple properties together with streaming support.
This breaks the feature introduced by #187.

Can this be enabled again anytime soon?

**Comment by adamribaudo-velir** [comment]
I started working on this but there's a problem...

dbt needs to know if the intraday tables exist at compile time in order to evaluate the `source_intraday` CTE in `base_ga4__events`.

But the intraday tables are not copied into the destination dataset until after the `combine_property_data()` macro has run at runtime.

We could add a user variable back in saying `union_intraday_events` true or false, but I would love for the solution to just work without additional configuration. Any ideas?

**Comment by adamribaudo-velir** [comment]
Figured this out (I think). Fix is in https://github.com/Velir/dbt-ga4/pull/257
