### ISSUE TITLE
Do we have session-scoped attribution available to report on?

### ISSUE THREAD

**Issue by niteshsharoff** [Velir/dbt-ga4#263]
Hey,

I've just added this on and I was curious whether some of these were considered?

https://tanelytics.com/ga4-bigquery-session-traffic_source/
https://adswerve.com/blog/ga4-bigquery-tips-guide-to-attribution/

My client is after session-scoped last click and user scoped first-click for each eCom purchase, curious if the have the first one somewhere?

**Comment by dgitis** [comment]
The `session_x` columns are last click.  The `user_x` columns are first click. The `last_non_direct_x` columns are last, non-direct. 

That's all that we have. We don't have position-based, decay, or data-driven. 

Feel free to add those and submit a pull request if you value any of them.

**Comment by niteshsharoff** [comment]
Thanks @dgitis, 

To produce a first_click, last_click report for purchase transactions, would you recommend:
1. Enable recommended events (`purchase`)
2. Join `stg_ga4__event_purchase` with `stg_ga4__sessions_traffic_sources_last_non_direct_daily` using `session_key`
3. Use `user_medium` from purchase table and `session_medium` from last non direct daily
4. (Optional) match `user_medium` with seeded csv for channel groupings to extract default channel grouping

Is this the best way?

**Comment by dgitis** [comment]
We don't really have a good example because we leave it to you to decide and that's a fair decision. However, if you ask me what I'd do, then it would look something like this.

Enable the purchase event. You can add custom parameters to it if you want so why not?

I'd materialize your events as partitioned tables naming them either `fct_ga4__event_event_name` or `evnt_ga4__event_name`. The second is what I recommend because we're not adhering to star-schema so the `fct_*` name is somewhat misleading. Those tables would be partitioned by date. After materialising as partitioned tables, then I'd join them because the staging models hit the base tables which contain all of the data. Splitting the `stg_ga4__event_*` tables into `fct_*` or `evnt_*` tables reduces the processing required to generate reports because you are only hitting the relevant event tables. Remember that the staging views roll back up to the `base_ga4__events` table so you need to materialise a downstream layer as  something other than a view so that your reports don't hit the raw event tables.

After that, it depends on the reporting requirements, but I'd probably join the session tables to `fct_` or `evnt_` event  tables in a View to minimise the effort required of the data viz person while fixing cross-partition metrics.

**Comment by dgitis** [comment]
So, to be more clear. Materialise event tables as partitioned tables and join them with the `session_daily` table as that holds both `session_` and `user_x` attribution data. Just remember that the session data isn't last, non-direct. That's `last_non_direct_x`.

**Comment by niteshsharoff** [comment]
Thanks @dgitis! Very helpful :)
