### ISSUE TITLE
Derived session properties

### ISSUE THREAD

**Issue by willbryant** [Velir/dbt-ga4#54]
`derived_user_properties` is excellent and exactly what I needed for some of my properties that once set don't really change.

But we also have some event params that will most likely be different for each session, and putting them in `derived_user_properties` means we overwrite the old values for old sessions, which is not right for our data. For example, our shipping time estimates are per-session.

So I'd like to add `derived_session_properties`.

Do you think it's worth waiting for #46 to go in before working on this? That looks pretty major so some risk of a merge conflict, but also looks a bit stalled?

**Comment by dgitis** [comment]
Hi @willbryant, I'm responsible for #46. It makes some big changes that we should discuss. I've been very busy lately with a lot of things but I will start to have time to push this to where it can be merged next week. I would expect a timeline of about 2-3 weeks before we can merge it.

Alternately, you can create a new branch from #46 instead of main and build off of that and then be sure to merge after we've resolved #46.

**Comment by willbryant** [comment]
Righto, thanks @dgitis.

Since #46 is a few weeks off, I took a closer look and realised that you weren't changing the derived user properties staging model, and it turns out I don't actually need to change any conflicting lines in the session tables, so I believe my PR will merge OK with yours. I'll submit it now.
