### ISSUE TITLE
Events not associated with session correctly when user_id changes

### ISSUE THREAD

**Issue by willbryant** [Velir/dbt-ga4#61]
We're noticing that some events are associated with `session_key` values that do not appear in `dim_ga4__sessions`.

If I run this query:

```
SELECT event_date_dt, event_name, user_pseudo_id, user_id, user_key, ga_session_id, session_key
from `delivereasy-data-prod`.`bi_dbt_ga4`.`stg_ga4__events`
where user_pseudo_id = '1hzXd+Z2R1....' and event_date_dt = '2022-09-01'
order by event_timestamp
```

We can see why:

<img width="863" alt="Screen Shot 2022-09-05 at 22 49 58" src="https://user-images.githubusercontent.com/12062/188432317-14e38fde-164c-45bb-8e1e-542d4fa47d87.png">

GA4 has not managed to copy the `user_id` back to the start of the session (which I thought it was meant to do TBH, but there you go).

Therefore, the `user_key` has been reset when the user logs in and their `user_id` goes from `NULL` to set. This, in turn, causes `session_key` to change.

Finally, because this new session does not have a `session_start` event, because it is not a new session from GA4's perspective, the second session is generated in the `fct_ga4__sessions` table but *not* in the `dim_ga4__sessions` table.

As a result, queries that join across to `dim_ga4__sessions` drop the event rows (or miss data, if we use a left join).

**Comment by willbryant** [comment]
My first attempt (see that commit 64a749b) was to try and use user_pseudo_id instead of user_key here. But that doesn't work either as we then get two rows in fct_sessions for the two user_key values.

I guess my question is why we even have user_key? Is user_pseudo_id not sufficiently unique per stream_id?

**Comment by willbryant** [comment]
Further complicating the session problem, https://support.google.com/firebase/answer/9191807?hl=en describes how sometimes we lose a session_start event, and I see that in my data. It's a small fraction, but I have over 2000 such sessions.

What do we need from the session_start events? The code says they don't even have the properties we need on them.

**Comment by adamribaudo-velir** [comment]
You're raising two issues. Let me address them independently:

**Value and dependability of a `user_key` field**

The intention here was to provide a single identifier for a "user", knowing that in some cases a "user" is defined by their `user_id` and in other cases a "user" can only be defined by their `user_pseudo_id`. The ultimate goal was to provide aggregate metrics at a "user" level, allowing for both definitions. 

The fact that the user_key changes mid-session shows that the implementation is too brittle. A more robust implementation would use a mapping table that tracks how each `user_pseudo_id` maps back to 0 or 1 `user_id`'s (handling many-many mappings would require an identity graph and is super complicated to maintain). In this implementation, the `session` mart tables would only care about `user_pseudo_id` given the assumption that a single session can only be associated with 1 "user". `user` mart tables, however, would use the mapping table to relate to session and allow aggregation across sessions.  

I created https://github.com/Velir/dbt-ga4/issues/62 to better hone in on this task. 

**Value and dependability of a `session_start` event**

It's frustrating that we can't depend on a `session_start` event, but I'm in the progress of re-writing the `sessions` mart tables to use an incremental strategy and I'm finding it necessary to easily find the start of each session without window functions. Scanning the `stg_ga4__events` model for the `session_start` is the best option I have found so far. The root issue is that session can span multiple days, so we need to incrementally load sessions while respecting the `day` grain partitioning in the `base_ga4__events` table. 

All that to say that allowing for incremental loading of sessions may supersede the data quality issue you raised. But there's a chance I/we find a better way.

**Comment by willbryant** [comment]
Yeah, it's a tough one. Could we attack the problem with an extra stage?

If we were to generate "daily sessions" as (date partition, stream_id, user_pseudo_id, ga_session_id) sets, and then roll them up to sessions by looking back to the one previous partition to see if there is a matching tuple?

The session timeout in GA4 is configurable but the max is 7h:55, so if we don't find a session from the previous day partition, we don't need to look back any further.

**Comment by dgitis** [comment]
Just to add to the complexity, we might want to think about supporting
session stitching while we fix this.

I was thinking we might want a table similar to the one Will describes that
maps user_id, user_pseudo_id, and stream_id to use to re-generate the
user_keys. I was thinking this would be incremental, but not partitioned.
And we'd use that to lookup which user_pseudo_ids map to which user_ids and
use that mapping to generate the user_keys rather than mapping in the event
which is causing the problems that Will identified.

The advantage of this method is that it would allow session stitching. dbt
has some don't update these fields flags that you can use. We could use
that feature combined with a boolean regenerate-user-key variable and then
modify our models so that we have incremental, full-refreshes, and
regenerate-user-key refreshes that are full refreshes but only update
user_keys.

This would let us map old sessions on devices that started with just the
user_pseudo_id before finally signing in and creating a user_id to those
new user IDs. Then, you could run a weekly or monthly job to fix all of the
old user_keys that have come in with new user_id to user_pseudo_id mappings
using a vars command-line declaration (dbt run --vars
{'regenerate-user-key':'true'}  ).

The disadvantages are complexity, performance, and the need to update all
of our non-view models to support the new update type against both the
user-key changing within a session and improving cross-session user-key
mappings.



[image: Damon Gudaitis, Principal at Caret Juice Marketing]

*Damon Gudaitis*
Principal, Caret Juice Marketing
www.caretjuice.com
e: ***@***.*** | p: 778-846-9248
