### ISSUE TITLE
Example using Snowflake

### ISSUE THREAD

**Issue by tomredman** [Velir/dbt-ga4#72]
Is it possible to use this package with Snowflake as the data warehouse? If so, what would the settings be?

Thanks in advance!

**Comment by adamribaudo-velir** [comment]
Hi Tom, likely not because we hadn't considered that use case and have implemented some BQ-specific commands such as _TABLE_SUFFIX.

Just curious, how are you going about replicating your GA4 data to Snowflake?

From: Tom Redman ***@***.***>
Sent: Friday, October 7, 2022 11:17 AM
To: Velir/dbt-ga4 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Velir/dbt-ga4] Example using Snowflake (Issue #72)


Is it possible to use this package with Snowflake as the data warehouse? If so, what would the settings be?

Thanks in advance!

-

**Comment by tomredman** [comment]
Thanks for the quick reply! We're using a Fivetran connection to take the GA4 data and push it to Snowflake.

**Comment by zachrenwick** [comment]
The Fivetran connector for GA4 does not load the data in the same schema necessary for this dbt project to transform the data: 
https://fivetran.com/docs/applications/google-analytics-4#schemainformation

This project is built upon raw, hit/event level data whereas the Fivetran connnector looks to aggregate only specific dimensions and measures you select.

The bigger issue here is getting access to the raw clickstream data :)

**Comment by adamribaudo-velir** [comment]
Zach is exactly right. Using Fivetran in many ways negates needing to use this package because your raw data has already been transformed into modeled data.

**Comment by tomredman** [comment]
Indeed! I see it's pulling in a number of reports already. Thank you all!
