### ISSUE TITLE
Not enough resources for query planning

### ISSUE THREAD

**Issue by clemens7haar** [Velir/dbt-ga4#97]
In the default configuation building the fct_ga4__pages model fails due to this message:

`Resources exceeded during query execution: Not enough resources for query planning - too many subqueries or query is too complex`

![image](https://user-images.githubusercontent.com/20857437/203935292-b674a9d4-07b3-4fe6-a751-c0878db076ff.png)

It's a really big database and I'm using the daily+streaming setting. After defining materialize table for base_ga4__events_intraday it works again, but I'm not sure if it's the best way to solve it. What would you recommend?

![image](https://user-images.githubusercontent.com/20857437/203936652-e96950e5-5917-442a-ba43-7c2d093597fb.png)

**Comment by adamribaudo-velir** [comment]
Interesting. I know @dgitis is using this model on a large instance, but I believe he's only using the "streaming" option rather than "daily+streaming"

The only risk I can think of in materializing the intraday data as a table is freshness. You'll need to rerun dbt to see any newly streamed events. Seems like a solid work-around for now that doesn't require editing any package source files.

**Comment by willbryant** [comment]
The cause of these errors is the number of CTEs and joins. You are more likely to run into these if you have a lot of "conversions" defined because the current implementation makes one CTE + join per "conversion". The size of the data shouldn't have any direct impact.

I fixed similar errors in other models in 746e949 and 300b926. I haven't run into this case myself as I don't use the pages model, so I have it disabled . But I think that in principle you should be able to apply a similar fix - count all the conversions in a single pass.

**Comment by adamribaudo-velir** [comment]
I don't have a good way to test this, but if @willbryant is right, #98 should fix this
